sudo: required

services:
  - docker

before_install:
  - cd 2.1.1
  - docker build -t couchdb:2.1.1 .

script:
  - docker run -d -p 6984:6984 couchdb:2.1.1 && sleep 5 && curl -k https://localhost:6984/
